Remove unused functionality and tests
ASFHyP3/hyp3-lib pull request #286
Opened 2024-01-04 15:26 UTC by forrestfwilliams

This PR will be the first of several, which will attempt to modernize hyp3lib for its current usage. This first PR removes all functionality not currently being using by one of these GitHub orgs:

ASFHyP3, asfadmin, ASFOpenSARLab, access-cloud-based-insar, dbekaert

All of the remaining tests are passing.

The removed files include:
- hyp3lib/apply_wb_mask.py
- hyp3lib/area2point.py
- hyp3lib/asf_geometry.py
- hyp3lib/asf_time_series.py
- hyp3lib/copy_metadata.py
- hyp3lib/createAmp.py
- hyp3lib/cutGeotiffsByLine.py
- hyp3lib/dem2isce.py
- hyp3lib/draw_polygon_on_raster.py
- hyp3lib/enh_lee_filter.py
- hyp3lib/etc/__init__.py
- hyp3lib/etc/config/get_dem.cfg
- hyp3lib/etc/lut/change.lut
- hyp3lib/etc/lut/glacier_tracking.lut
- hyp3lib/extendDateline.py
- hyp3lib/file_subroutines.py
- hyp3lib/geotiff_lut.py
- hyp3lib/getBursts.py
- hyp3lib/getDemFor.py
- hyp3lib/getSubSwath.py
- hyp3lib/get_bb_from_shape.py
- hyp3lib/get_bounding.py
- hyp3lib/get_dem.py
- hyp3lib/ingest_S1_granule.py
- hyp3lib/iscegeo2geotif.py
- hyp3lib/makeChangeBrowse.py
- hyp3lib/makeColorPhase.py
- hyp3lib/makeKml.py
- hyp3lib/make_arc_thumb.py
- hyp3lib/make_cogs.py
- hyp3lib/offset_xml.py
- hyp3lib/par_s1_slc_single.py
- hyp3lib/ps2dem.py
- hyp3lib/rasterMask.py
- hyp3lib/raster_boundary2shape.py
- hyp3lib/rtc2color.py
- hyp3lib/rtc2colordiff.py
- hyp3lib/simplify_shapefile.py
- hyp3lib/subset_geotiff_shape.py
- hyp3lib/system.py
- hyp3lib/tileList2shape.py
- hyp3lib/verify_opod.py
- tests/data/test_ned13_dem.tif
- tests/data/test_srtmgl1_antimeridian_dem.tif
- tests/test_getSubSwath.py
- tests/test_get_bounding.py
- tests/test_get_dem.py
- tests/test_make_cogs.py
- tests/test_system.py

2024-01-04 19:43 UTC, jhkennedy requested changes
When looking at the deletions, I see at least 5 (I stopped here) modules being removed that are used in one of our repositories:
1. `createAmp.py`: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/rtc/rtc_sentinel.py#L20
2. `make_cogs.py`: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/rtc/rtc_sentinel.py#L25
3. `raster_boundary2shape.py`: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/rtc/rtc_sentinel.py#L26
4. `rtc2color.py`: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/rtc/rtc_sentinel.py#L27
5. `system.py`: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/rtc/rtc_sentinel.py#L28

We should revisit the methodology used to determine what modules/functions are used across the orgs.

2024-01-04 20:47 UTC, forrestfwilliams commented
Thanks for the catch @jhkennedy. My script failed to find all the results because of [this bug in the GitHub CLI](https://github.com/cli/cli/issues/8522).

2024-01-04 22:05 UTC, forrestfwilliams commented
Everything has been added back!

2024-01-04 22:37 UTC, jhkennedy requested changes
I caught one more removed-but-used module

2024-01-04 22:37 UTC, jhkennedy commented on hyp3lib/par_s1_slc_single.py
This module is used in hyp3-gamma here:
https://github.com/ASFHyP3/hyp3-gamma/blob/develop/hyp3_gamma/insar/ifm_sentinel.py#L20

2024-01-04 22:37 UTC, jhkennedy commented on hyp3lib/par_s1_slc_single.py
Notably, `ifm_sentinel.py` also had many `hyp3lib` imports

2024-01-04 22:37 UTC, jhkennedy commented on hyp3lib/cutGeotiffs.py
It looks like this is mentioned in insarlab/MintPy documentation (the only hit for hyp3lib):
https://github.com/search?q=org%3Ainsarlab%20hyp3lib&type=code

I don't think that's enough to keep the file, but we'll want to make a PR there to change it -- maybe as part of this (?): insarlab/MintPy#1004

2024-01-04 23:17 UTC, jhkennedy commented on setup.py
>          'get_asf.py = hyp3lib.get_asf:main',
What's still using `get_asf.py`?

2024-01-04 23:28 UTC, jhkennedy commented on setup.py
>          'get_asf.py = hyp3lib.get_asf:main',
Similarly, what's still using `metadata.py`?

2024-01-05 13:13 UTC, forrestfwilliams commented on hyp3lib/cutGeotiffs.py
Yep, that's bad information anyway. I think we should remove the functionality and change the docs.

2024-01-05 13:41 UTC, forrestfwilliams commented
@jhkennedy this is ready for your re-review!

2024-01-05 18:59 UTC, jhkennedy approved these changes
Everything looks good now! PyCharm inspection also doesn't find anything worrying specific to these changes (thought here's *a lot* we should clean up):
![image](https://github.com/ASFHyP3/hyp3-lib/assets/7882693/ac7a2e81-060c-489c-bf1c-31ba7c808dd9)

@forrestfwilliams did you update the PR comment to reflect the final changes?

2024-01-05 19:51 UTC, forrestfwilliams commented
Yep, updated!

2024-01-05 19:51 UTC, merged